### PR TITLE
Ubuntu Core support

### LINKED ISSUE #40: Feature request: Split Personality Snap
Just saw this blog post: [https://snapcraft.io/blog/split-personality-snaps](https://snapcraft.io/blog/split-personality-snaps), that mentions a way of creating snaps that can both work as appliances on top of Ubuntu Core and as normal applications ot top of regular Ubuntu Desktop, and wondered if it could apply to RetroArch.

I am currently a Lakka user but would be interested to explore the Ubuntu option for the sake of installing additional services alongside RetroArch (installed on a pc - not a RPI).

### PR DESCRIPTION
**Pull request by viachaslavic**
## Description

Add basic support the daemon mode based on the [iot-example-graphical-snap template](https://github.com/canonical/iot-example-graphical-snap), but with the support of both Wayland and KMS/DRM.

## Related issues:

~~Fix https://github.com/libretro/RetroArch/issues/16730~~ (already fixed in #57)
Close #40

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
is this one all ready to go?

**Comment by viachaslavic** [comment]
Yes, at this stage it is ready. But there is a [issue](https://github.com/libretro/RetroArch/issues/16890) with the implementation of the Wayland client in the code.

P.S. Following "best practices" I moved the _snapcraft.yaml_ file to the _snap_ directory, but the building, as before, must be runned from the root of the repository

**Comment by hizzlekizzle** [comment]
k, let's try it!

**Comment by hizzlekizzle** [comment]
looks like adding the daemon field alongside the browser-support attribute triggered a manual review, which we failed:

> (NEEDS REVIEW) 'daemon' should not be used with 'browser-support' security-snap-v2_daemon_with_browser-support (daemon)
> 
> Please adjust the snap without the use of `daemon` and `browser-support`

Can we just remove browser-support? I don't even remember why it's there, honestly.

**Comment by viachaslavic** [comment]
According to the documentation, this interface use a browser API, not just an HTTP client. I also do not remember similar abilities in RA. I guess, we can try to exclude it for daemon, making a separate `plugs` list instead of the anchor.

**Pull request merged**
